language: csharp
solution: PushStream.sln
sudo: false
dist: trusty
branches:
  only:
  - master
mono:
  - latest
before_install:
  - cd ./src
script:
  - xbuild /p:Configuration=Debug PushStream.sln
  - mono ./PushStream.Test/bin/Debug/PushStream.Test.exe



